### ISSUE TITLE
Change `pluck` to `map` in all the code snippets

### ISSUE THREAD

**Issue by josepot** [re-rxjs/react-rxjs.org#31]
TIL that `pluck` will be flagged as deprecated on RxJS v7 and it will be removed on RxJS v8.

Also, it's a bit "too clever" to be used on the tutorial... Meaning that everyone is familiar with `map`, but not everyone is familiar with `pluck`. So, I think that we should stop using it.

I don't have time right now to do that. So, I'm opening this issue so that we don't forget.

**Comment by voliva** [comment]
I'll do that :)
