### ISSUE TITLE
Repo for example Todo App?

### ISSUE THREAD

**Issue by hoclun-rigsep** [re-rxjs/react-rxjs.org#42]
I would attempt to update this app to avoid the deprecated API members. Is there a repo I can push to or fork/pr?

**Comment by voliva** [comment]
We have one for the github issues viewer [re-rxjs/react-rxjs-github-issues-example](https://github.com/re-rxjs/react-rxjs-github-issues-example) but we don't have it for the todos example.

From your PR #44 I see you've created a repo with the new todos in here [hoclun-rigsep/react-rxjs-basic-todos](https://github.com/hoclun-rigsep/react-rxjs-basic-todos). Is it cool if we fork it into re-rxjs organization, and then new contributions can be added there? - I will hold off until you think it's ready, I don't want to add friction.

We would also try to create a single repo that will contain all of the small recipes we want to add on the new docs site... I think creating one repo per each one of them is a bit overkill

**Comment by hoclun-rigsep** [comment]
> Is it cool if we fork it into re-rxjs organization, and then new contributions can be added there?

Of course. I'll look it over again but as far as I can see it is ready.

**Comment by voliva** [comment]
We just forked it to https://github.com/re-rxjs/react-rxjs-basic-todos. Thanks for pointing this out!
